# config.yaml

## Where the samples will be written
save_data: data-mt/run/example
## Where the vocab(s) will be written
src_vocab: data-mt/run/example.vocab.src
tgt_vocab: data-mt/run/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: True

# Corpus opts:
data:
    corpus_1:
        path_src: data-mt/src-train.txt
        path_tgt: data-mt/tgt-train.txt
    valid:
        path_src: data-mt/src-val.txt
        path_tgt: data-mt/tgt-val.txt

# Vocabulary files that were just created
src_vocab: data-mt/run/example.vocab.src
tgt_vocab: data-mt/run/example.vocab.tgt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: data-mt/run/model
save_checkpoint_steps: 500
train_steps: 1000
valid_steps: 500

seed: 42